### ISSUE TITLE
Not showing Product Backlog Items

### ISSUE THREAD

**Issue by dalefrancis88** [mikaelkrief/VSTS-Extension-ScrumReport#4]
I have a query set up that is showing product backlog items with appropriate change dates but the report is only showing the epics, features and tasks and DONE product backlog items. It doesnt show ones that are Active or Committed, even though they are shown in the query

**Comment by mikaelkrief** [comment]
@dalefrancis88 : the fixe of your bug is in progress

**Comment by mikaelkrief** [comment]
@dalefrancis88 : this bug is fixed
