### ISSUE TITLE
Empty Page in Google Chrome, SecurityError, TypeError

### ISSUE THREAD

**Issue by jenshavelberg** [mikaelkrief/VSTS-Extension-ScrumReport#5]
![2016-03-10_174925](https://cloud.githubusercontent.com/assets/6579164/13676997/826adebe-e6e8-11e5-88a8-c21dd1bdc5e4.png)

**Comment by mikaelkrief** [comment]
I Investigate

**Comment by jenshavelberg** [comment]
thank you!

**Comment by jenshavelberg** [comment]
any news?

**Comment by mikaelkrief** [comment]
HI Jess, What is the target where you installed the extension  : VSTS or TFS 2015 on premise ?

**Comment by jenshavelberg** [comment]
TFS 2015 on premise!

**Comment by mikaelkrief** [comment]
ah, yes, we know that we have a issue with appInsight with extensions on TFS2015 on premise.
I'll see if we have news about this issue.
I come back to you quickly.

**Comment by mikaelkrief** [comment]
Hi Jess, this bug is fixed, I test on TFS 2015 Update 2 and is ok.
Redownload the extension , and update it .

**Comment by jenshavelberg** [comment]
Hi mikael,
is the language a problem? We use a german tfs. 
See the following error:

> Error the query is not found :
> Create the query 'Scrum Report' on the root on Shared Queries folder
 

![image](https://cloud.githubusercontent.com/assets/6579164/14239680/7cd0c54a-fa3e-11e5-8fbc-d2d9dc368f09.png)

Can you help me?

**Comment by jenshavelberg** [comment]
thank you!
